# ==========================================
# KONFIGURASI DATABASE POSTGRESQL
# ==========================================
# Beri tahu Spring jenis driver dan URL-nya
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_gateway?sslmode=disable

# Kredensial Database
spring.datasource.username=postgres
spring.datasource.password=12345

# ==========================================
# KONFIGURASI HIBERNATE / JPA
# ==========================================
# Beri tahu Hibernate "Dialect" (bahasa spesifik) PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Otomatis membuat/update tabel di database
spring.jpa.hibernate.ddl-auto=update

# Menampilkan query SQL di terminal (untuk debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true